title: Simbrain Docs
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://www.simbrain.net/

aux_links:
  Simbrain Repository: https://github.com/simbrain/simbrain

mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "9.1.3"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - dev-server.sh